# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
